# Cleaning/Harmonizing Corpora & Add the language codes from the formulars

Work done in this notebook:
- exploration of the useful statistics
- remove unnecessary columns from dataframes
- insert col for ISO codes
- concat dataframes per corpora
- insert col for corpora

- isolate texts and count the number of sent. (moy/var.) per LANG
  
- dowload the four dataframes (one per langauge)

#### Importations

In [149]:
!pip uninstall numpy spacy -y
!pip install "numpy==1.26.4"
!pip install spacy

Found existing installation: numpy 1.24.4

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\Elise\\AppData\\Local\\Temp\\pip-uninstall-vp9dlhx9\\linalg\\_umath_linalg.cp311-win_amd64.pyd'

Uninstalling numpy-1.24.4:
  Successfully uninstalled numpy-1.24.4
Collecting numpy==1.26.4
  Obtaining dependency information for numpy==1.26.4 from https://files.pythonhosted.org/packages/3f/6b/5610004206cf7f8e7ad91c5a85a8c71b2f2f8051a0c0c4d5916b76d6cbb2/numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/15.8 MB 5.9 MB/s eta 0:00:03
   - -------------------------------------- 0.4/15.8 MB 5.1 MB/s eta 0:00:04
   - -------------------------------------- 0.7/15.8 MB 5.2 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/15.8 MB 5.3 MB/s eta 0:00:03
   -- ------------------------------------- 1.2/15.8 MB 5.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.4/15.8 MB 5.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.7/15.8 MB 5.3 MB/s eta 0:00:03
   ---- ----------------------------------- 2.0/15.8 MB 5.4 MB/s eta 0:00:03
   ----- ---------------------------------- 2.2/15.8 MB 5.4 MB/s eta 0:00:03
   ------ --------------------------------- 2.5/15.8 MB 5.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.7/15.8 MB 5.5 MB/s eta 0:00:03
   ------- -------------------------------- 3.1/15.8 MB 5.6 MB/s eta 0:00:03
   -------- ------------------------------- 3.3/15.8 MB 5.6 MB/s eta 0:00:03
   -------- ------------------------------- 3.5/15.8 MB 5.5 MB/s eta 0:00:03
   --------- ------------------------------ 3.7/15.8 MB 5.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.0/15.8 MB 5.5 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/15.8 MB 5.4 MB/s eta 0:00:03
   ----------- ---------------------------- 4.6/15.8 MB 5.5 MB/s eta 0:00:03
   ------------ --------------------------- 4.9/15.8 MB 5.5 MB/s eta 0:00:02
   ------------ --------------------------- 5.0/15.8 MB 5.5 MB/s eta 0:00:02
   ------------- -------------------------- 5.4/15.8 MB 5.5 MB/s eta 0:00:02
   -------------- ------------------------- 5.6/15.8 MB 5.5 MB/s eta 0:00:02
   -------------- ------------------------- 5.9/15.8 MB 5.5 MB/s eta 0:00:02
   --------------- ------------------------ 6.1/15.8 MB 5.6 MB/s eta 0:00:02
   ---------------- ----------------------- 6.4/15.8 MB 5.6 MB/s eta 0:00:02
   ---------------- ----------------------- 6.7/15.8 MB 5.6 MB/s eta 0:00:02
   ----------------- ---------------------- 7.0/15.8 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.8 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 7.5/15.8 MB 5.6 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.8 MB 5.6 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.8 MB 5.6 MB/s eta 0:00:02
   --------------------- ------------------ 8.3/15.8 MB 5.7 MB/s eta 0:00:02
   --------------------- ------------------ 8.6/15.8 MB 5.6 MB/s eta 0:00:02
   ---------------------- ----------------- 9.0/15.8 MB 5.7 MB/s eta 0:00:02
   ----------------------- ---------------- 9.2/15.8 MB 5.7 MB/s eta 0:00:02
   ------------------------ --------------- 9.5/15.8 MB 5.7 MB/s eta 0:00:02
   ------------------------ --------------- 9.8/15.8 MB 5.7 MB/s eta 0:00:02
   ------------------------- -------------- 10.1/15.8 MB 5.7 MB/s eta 0:00:01
   -------------------------- ------------- 10.4/15.8 MB 5.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.7/15.8 MB 5.8 MB/s eta 0:00:01
   --------------------------- ------------ 10.9/15.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------- ----------- 11.2/15.8 MB 5.7 MB/s eta 0:00:01
   ---------------------------- ----------- 11.2/15.8 MB 5.6 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.8 MB 5.7 MB/s eta 0:00:01
   ----------------------------- ---------- 11.7/15.8 MB 5.7 MB/s eta 0:00:01
   ------------------------------ --------- 12.0/15.8 MB 5.7 MB/s eta 0:00:01
   ------------------------------ --------- 12.2/15.8 MB 5.7 MB/s eta 0:00:01
   ------------------------------- -------- 12.3/15.8 MB 5.5 MB/s eta 0:00:01
   ------------------------------- -------- 12.6/15.8 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 12.7/15.8 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 13.0/15.8 MB 5.5 MB/s eta 0:00:01
   --------------------------------- ------ 13.2/15.8 MB 5.5 MB/s eta 0:00:01
   --------------------------------- ------ 13.4/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 13.8/15.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.0/15.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.2/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 14.5/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 14.7/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.0/15.8 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 15.2/15.8 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 15.4/15.8 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  15.6/15.8 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 4.7 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.1
    Uninstalling numpy-2.4.1:
      Successfully uninstalled numpy-2.4.1

ERROR: Could not install packages due to an OSError: [WinError 5] Accès refusé: 'C:\\Users\\Elise\\anaconda3\\Lib\\site-packages\\~umpy.libs\\libscipy_openblas64_-9e3e5a4229c1ca39f10dc82bba9e2b2b.dll'
Consider using the `--user` option or check the permissions.

Requirement already satisfied: spacy in c:\users\elise\anaconda3\lib\site-packages (3.7.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (8.2.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (5.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (4.65.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (1.10.8)
Requirement already satisfied: jinja2 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in c:\users\elise\anaconda3\lib\site-packages (from spacy) (68.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\elise\appdata\roaming\python\python311\site-packages (from spacy) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (3.3.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\elise\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\elise\appdata\roaming\python\python311\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\elise\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\elise\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\elise\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\elise\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\elise\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\elise\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.4)
Requirement already satisfied: colorama in c:\users\elise\appdata\roaming\python\python311\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\elise\anaconda3\lib\site-packages (from typer<0.10.0,>=0.3.0->spacy) (8.0.4)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in c:\users\elise\anaconda3\lib\site-packages (from weasel<0.4.0,>=0.1.0->spacy) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\elise\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.1)

In [78]:
import pandas as pd
import numpy as np 
import spacy

### 1. Importation of the files, exploitation of the statistics, removal of unnecessary data
#### a. Files' importation

In [3]:
df_fnw_gcf = pd.read_csv("fineweb2_gcf_concat.csv")
df_fnw_gcr = pd.read_csv("fineweb2_gcr_concat.csv")
df_fnw_hat = pd.read_csv("fineweb2_hat_concat.csv")
df_glotcc_gcf = pd.read_csv("glotcc_gcf.csv")
df_glotcc_gcr = pd.read_csv("glotcc_gcr.csv")
df_glotcc_hat = pd.read_csv("glotcc_hat.csv")

In [7]:
df_fnw_gcf

,text,id,media,metadata
0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",<urn:uuid:8b665f6d-1ec7-413f-9560-fbd0b941d22f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://gen..."
1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",<urn:uuid:a6ef2d6f-d2d6-4fa4-9f50-d0f0a10b4396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://ord..."
2,Man pé palé di Jean Bernabé an manniè ki lib d...,<urn:uuid:f8a9a3d0-268c-4b0c-9ba4-6d439484a396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,<urn:uuid:45222417-204e-456c-8f4f-039d1210c351>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",<urn:uuid:e487404b-555a-4459-ad01-5c66f450a070>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
5,"Mas An Nou, sé Mas a neg <...>, sé Mas a moun ...",<urn:uuid:8eace61a-1191-463b-bc70-bb0b54b56f9f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://mas..."
6,"Messié, Dam, sé MetoBôkay ka palé ba zôt!\nDé ...",<urn:uuid:1661751a-bdeb-4d60-a524-4e50ab8fc32c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://met..."
7,"Dèpi lendi, an monté ba zòt on blòg ww otila a...",<urn:uuid:96d834b7-93b8-4643-9ab4-e479d71e2aab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://sha..."
8,« Bobòn fwa… Twa fwa bel kont ! »\nRann sèvis ...,<urn:uuid:4d61ce30-164c-4b86-9d34-897fb209e916>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
9,[...]\nPa rapôt a travay oben pou dé rézon pli...,<urn:uuid:db19b73b-61a0-41aa-90d6-d44004580c76>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
10,"[...]\nPa ni an mwa, nou té ka vréyé bon labou...",<urn:uuid:485b0675-1c1f-4b41-89b6-47707fcf7f4a>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
11,"Shabine Glindor Miss Docterous Girl, yiw, 2012...",<urn:uuid:5cd2dc22-16b8-4267-b9ab-c36c59186f26>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
12,"[...]\nMÉ KA KI FĒ YO ÉGRI KON SA, NON ?\nMé k...",<urn:uuid:4ca9dd6b-5a05-4347-acbe-254c521e8a4c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
13,"[...]\nManman, ou pi réel ki pagna, Manman, sé...",<urn:uuid:0bd9d00e-459c-44d0-b75a-59e3ee42a032>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
14,Sé dépi lanné 2.000 an asosiyasion Chinwa l’Af...,<urn:uuid:b58e621b-2f14-49c9-b335-e76b338f92b6>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
15,"Yeah !! Brasco (Brasco)\n\nHey gué ca, tala sé...",<urn:uuid:3c8ba6a5-db13-4c9b-ae42-07ba3a815733>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
16,Jédi pasé (17/06) tout lari <...> té tou kam. ...,<urn:uuid:d876e575-e705-44b5-91db-d96e6e299e5e>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://gen..."
17,Sé jou-tala pétrolet Madinina an vèdet. Sé cho...,<urn:uuid:d3ca1c60-a08c-4e9d-a875-ba05ab75d03a>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
18,an chèché ... an pas touvé ...\nalò .... an ka...,<urn:uuid:18e81c5b-1631-4900-b659-b6b4721c7cb8>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
19,Man pé ké mélanjé sa ou fè an politik épi sa’w...,<urn:uuid:4cdfc40e-bac9-47ae-a1bc-e45971c638cf>,[],"{'dump': 'CC-MAIN-2014-23', 'url': 'http://www..."
20,"La mwen té près fin tout lantou en mwen, en té...",<urn:uuid:db6b202e-c9d6-4ab1-b36e-41f0e2c25ef0>,[],"{'dump': 'CC-MAIN-2014-42', 'url': 'http://www..."
21,[...]\nSi nou mandé enpé moun : ki moun ki Bro...,<urn:uuid:c138fc4e-6173-4ffc-9a22-e33a0cff2a0f>,[],"{'dump': 'CC-MAIN-2015-22', 'url': 'http://www..."
22,Léssé mwen diw jan ou té ka manké mwen\nLa nos...,<urn:uuid:15fab596-9108-479a-ac56-393d7b9dfa9a>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
23,"[...]\nJanklòd (Nouvèl / 'Gran Kozé'), sé on m...",<urn:uuid:a38aad9e-547b-4409-9cab-21c58c41320f>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
24,"On lè, fanm touvé-yo las pran kou anba men a n...",<urn:uuid:1df21096-5351-4e16-91eb-0677be57d943>,[],"{'dump': 'CC-MAIN-2016-36', 'url': 'http://dya..."
25,"Ki Amérendien, ki Afriken, ki Zendien, ki Blan...",<urn:uuid:714615e2-37b4-4af3-bdf6-e3dde81cafab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
26,[...]\nAnnou voyé kreyòl douvan douvan\n\nSime...,<urn:uuid:1c674fe2-d547-4528-a685-becee13c687c>,[],"{'dump': 'CC-MAIN-2017-13', 'url': 'http://pot..."
27,"Tini déserten moun, yo toujou ka chèché-touvé ...",<urn:uuid:5b227398-adf2-407e-9b99-373900017ef2>,[],"{'dump': 'CC-MAIN-2017-22', 'url': 'http://mon..."
28,[...]\nLè nou ka palé lendépandans ba moun ki ...,<urn:uuid:f16c0d4c-7b6b-49b3-b333-d2ed22260c8a>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://gwa..."
29,A pies kalté moman yo pa santi ki andidan pep-...,<urn:uuid:74d63b73-c97a-4532-8d67-2ce3f3b6e9cf>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://mon..."
30,"An mwa mé-la ki pasé la, té ni twa kongré ki f...",<urn:uuid:6cf1a325-4c44-49a3-9901-ad6f3cee8f8c>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'http://car..."
31,"[...]\nPè Louwa té ni on troupo bèf, enki bèl ...",<urn:uuid:288c580f-3a86-4688-a5ee-b9ee6a8c50d8>,[],"{'dump': 'CC-MAIN-2017-51', 'url': 'http://cre..."
32,"Pa plita ki an midi a, man tann an granmoun ka...",<urn:uuid:a6dc41d7-a049-4700-8471-1cd4a4e14b91>,[],"{'dump': 'CC-MAIN-2018-05', 'url': 'http://mon..."
33,Chalè té ka lévé anba wob Létisia kifè manzel ...,<urn:uuid:3717d539-2401-4c49-996a-a4ed542d7a80>,[],"{'dump': 'CC-MAIN-2018-22', 'url': 'http://www..."
34,"Chofè an retrè, mé pa laritret.\nSé sa tout sé...",<urn:uuid:eb73bd59-9ec3-483b-a89f-b7ccd06a8d74>,[],"{'dump': 'CC-MAIN-2019-04', 'url': 'http://mon..."
35,Tan ka bay. Mémwè ka chonjé. Wi ! Lot jou a la...,<urn:uuid:f3dcca57-69b7-4a70-b0bd-d4c53d8a75b1>,[],"{'dump': 'CC-MAIN-2019-22', 'url': 'http://mon..."
36,Pawòl-palé a moun Lésent é ta moun Déhé pa tou...,<urn:uuid:f2ec55cb-4315-4582-976d-79ddc8be0633>,[],"{'dump': 'CC-MAIN-2019-30', 'url': 'http://www..."
37,Gadé vidéo-a ki pli ba teks-tala ! Sa nou ka w...,<urn:uuid:84aceb86-c508-486a-a1da-df152d55bde4>,[],"{'dump': 'CC-MAIN-2019-51', 'url': 'http://mon..."
38,[...]\nOu té kont lenjistis kifè granbonnè ou ...,<urn:uuid:8b0b2c88-8970-4caa-bd63-0807af416b1b>,[],"{'dump': 'CC-MAIN-2020-16', 'url': 'https://ww..."
39,Dékouvè kijan réinyon an nou ka déwoulé é touv...,<urn:uuid:389ed822-57e3-4323-b9b6-ad87b85ecce8>,[],"{'dump': 'CC-MAIN-2020-50', 'url': 'https://ww..."
40,"Nou ka goumen pou siklotwon, nou ka goumen pou...",<urn:uuid:851cae32-94cf-4f5a-b228-3217aa84b8f9>,[],"{'dump': 'CC-MAIN-2021-04', 'url': 'http://www..."
41,"Dézienm bagay nou pé konstaté tou, sé ki l'Eko...",<urn:uuid:16940138-2bf9-41d3-8e31-e324112b8b0d>,[],"{'dump': 'CC-MAIN-2021-17', 'url': 'http://mon..."
42,"Jòdijou, kontel an zwézo yo démaré zel-li, lan...",<urn:uuid:2753ab82-728a-4d99-a233-5d1cb5b2d22c>,[],"{'dump': 'CC-MAIN-2021-43', 'url': 'https://ww..."
43,« Roch dan dlo pa konnet doulè roch dan solèy ...,<urn:uuid:3b0fd1d0-acac-4b4c-a9d6-c56f4a6d54bc>,[],"{'dump': 'CC-MAIN-2022-21', 'url': 'http://jud..."
44,[...]\n« Poutji man ka matjé an kréyol »\nMan ...,<urn:uuid:015c422e-5170-43c3-90d1-85a4af49665f>,[],"{'dump': 'CC-MAIN-2023-06', 'url': 'https://fo..."
45,[...]\nDégajé & Pwòpté\nTin plizyè jan pou pwo...,<urn:uuid:534f732a-490f-4b33-924a-2e4c8e9b619f>,[],"{'dump': 'CC-MAIN-2023-14', 'url': 'https://ww..."
46,Man té ka travay épi Maksimilien LIMINO. Misié...,<urn:uuid:bedd30ca-4e19-4cb3-a83f-204a8565623b>,[],"{'dump': 'CC-MAIN-2023-40', 'url': 'https://mo..."

In [9]:
df_fnw_gcr

,text,id,media,metadata
0,VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...,<urn:uuid:a75ceea1-b219-4638-8e00-02acb367c1db>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
1,Lé ven senk mè démildis tout éléktér Sirinamye...,<urn:uuid:466cbd4c-2ac3-428c-be47-7542f3a43441>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
2,"[...]\nALE LAVE TO PYE, RAFAYEL!!\nBABUN MOFU ...",<urn:uuid:db5e1e9c-cd46-4030-822f-557f8fb844bb>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
3,"[...]\nLé vent sis séktanm dé mil sét,annan vi...",<urn:uuid:c9a5e8cb-04ae-444a-bc44-8ce3bcf37cb4>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
4,Lo nou té wè lit bann moun-yan ki té jwenn ann...,<urn:uuid:179977e2-4c73-41e4-8447-326efedd77a0>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
5,KAYENN « MINING SYMPOSIUM »\nPoukisa yé rivé f...,<urn:uuid:8719f2ea-6a4e-459c-8012-7c44c83464ed>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
6,Mo ka sonjé pronmyè fwè mo tandé sa zafè rakab...,<urn:uuid:51309d23-10d0-4e75-9fe2-264dd61dad3e>,[],"{'dump': 'CC-MAIN-2016-50', 'url': 'http://rot..."
7,Annou voyé kreyòl douvan douvan\n[...]\nMakak ...,<urn:uuid:97c5c257-7738-4c86-9be6-125ba91028e3>,[],"{'dump': 'CC-MAIN-2017-13', 'url': 'http://www..."
8,Trwa variété di grenn di lanti kiltivé.\nSerte...,<urn:uuid:afa6132b-87d1-4a0c-b448-387ed6eca54d>,[],"{'dump': 'CC-MAIN-2017-34', 'url': 'https://in..."
9,"Mo té ké lé li sa artik-a ?\nChak lannen, Témw...",<urn:uuid:7153099e-e9d5-4f10-8f8b-e6dc070c88cd>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'https://ww..."
10,Mo té ké lé li sa artik-a ?\nLanmizik pou lado...,<urn:uuid:2ea90fcd-ec69-4fc4-87dc-8104092e9efd>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'https://ww..."
11,"Abandonnen sa ki mal (1 Corinthiens 6:9, 10)\n...",<urn:uuid:001ba7df-8042-48e3-8add-37765d0921e2>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'https://ww..."
12,Mo té ké lé li sa artik-a ?\nLiv ké brochir po...,<urn:uuid:f2bfd37d-85ec-410b-bd4b-16d8b17d8122>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'https://ww..."
13,[...]\nGrann Déprésyon-an (The Great Depressio...,<urn:uuid:d2d3d1ae-fcd2-41ab-adcb-67e7521c34c5>,[],"{'dump': 'CC-MAIN-2020-05', 'url': 'https://gc..."
14,[...]\nOun ion oben yon est sa roun atom oben ...,<urn:uuid:bbb0a98e-31c1-450b-a4fe-96d6b3b4b9a6>,[],"{'dump': 'CC-MAIN-2020-05', 'url': 'https://gc..."
15,[...]\nJé di sosyété-a sa roun jé ki ka pratik...,<urn:uuid:9fd27054-1b1f-468c-ac9b-96814f368d4b>,[],"{'dump': 'CC-MAIN-2020-05', 'url': 'https://gc..."
16,"[...]\nTablo péryodik dé éléman, égalman aplé ...",<urn:uuid:96ee8b29-40ec-47a5-8f6c-7c2cf89c5c24>,[],"{'dump': 'CC-MAIN-2020-05', 'url': 'https://gc..."
17,[...]\nNou ka aplé artiri ansanm-an dé arm kol...,<urn:uuid:37f83382-a0ea-4099-9d16-d77c19ad413b>,[],"{'dump': 'CC-MAIN-2020-10', 'url': 'https://gc..."
18,[...]\nEntéraksyon fèb-a (osi aplé fòs fèb é p...,<urn:uuid:d9728652-cb77-46a1-8670-020faadd72f6>,[],"{'dump': 'CC-MAIN-2020-34', 'url': 'https://gc..."
19,Sa paj ka konsèrné lannen 1156 di kalandriyé j...,<urn:uuid:0215ff2e-c9ab-45d8-b043-a12555dce18f>,[],"{'dump': 'CC-MAIN-2023-06', 'url': 'https://gc..."
20,Mé mo menm mo pa profité di sa bagaj-ya pyès. ...,<urn:uuid:8a62bb9a-1977-4b6e-8260-f0f22776af4b>,[],"{'dump': 'CC-MAIN-2024-10', 'url': 'https://wo..."

In [11]:
df_fnw_hat

,text,id,media,metadata
0,"[...]\nLOS ANGELES, USA (defend.ht) - Sèz Iniv...",<urn:uuid:f3edc588-d4bf-4cef-8d52-39301cc65c00>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
1,"Otorite nan Repiblik Demokratik Kongo, mande s...",<urn:uuid:788d7917-dbcf-4285-ada3-79f8a40dc36f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
2,"[...]\nSoti lane 1982 rive 2012, gad kòt Ameri...",<urn:uuid:d16d3508-920c-4ad2-ba40-c16f5ffd26c7>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://lib..."
3,Men non pitit Jakòb yo ki te desann avè l’ nan...,<urn:uuid:fdf2184e-27f6-4d9d-b071-aefd163d4413>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
4,Senatè Jean William Jeanty (Depatman Nip) deno...,<urn:uuid:c153f695-a8b5-422e-b6be-92c31368be14>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
5,Pèp Izrayèl la lage kò l’ ankò nan fè sa ki ma...,<urn:uuid:125edce0-843a-47a9-bbf5-ab81b01267ce>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
6,"Pou yo pa jwenn anyen pou yo repwoche nou, pou...",<urn:uuid:cae8e401-9d1e-4c15-85c6-de9f1e8f63ec>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
7,Anvan ou aplike\nPou fè sèten klinik nou yo al...,<urn:uuid:beb4db80-37df-4eb9-854f-d6d6547ef6f3>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
8,Powèm pa Edner Saint-Amour\nDeus ex machina\nP...,<urn:uuid:393182bd-3da5-44b7-a5f4-0967a8f1a659>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
9,[...] Gwo bagay kapab reyalize epi fado aleje ...,<urn:uuid:76901e7e-2ad6-402e-ac0c-0ca204e0668f>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'https://ww..."
10,[...]\nCitation\nJaf di: Koudetayis yo konnen ...,<urn:uuid:a88feee9-6719-401a-a096-2eed7f2a1b6b>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
11,Klike Kouri al nan byen vit kite sit sa a. Apr...,<urn:uuid:be839311-c2d3-47df-b7fa-bc5ac2771f16>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
12,[...]\nSIDA se yon maladi ki paka trete. Sa vl...,<urn:uuid:eef7345f-c11a-4166-bef4-7fb162c49fa5>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://ht...."
13,Rezidan yo ak vizitè yo kapab flannen nan tout...,<urn:uuid:cf3d0d6c-b8d8-4c80-aaef-19de432ceab2>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
14,[...] Nou dwe akeri kapasite pou nou wè moun n...,<urn:uuid:2b14c863-87df-416b-9e80-dc3948120f60>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'https://ww..."
15,"Creole 0.9.5 te lage pa twò lontan de sa, ak v...",<urn:uuid:ea2c3e21-00ff-4efc-89fe-555d1ba2bf62>,[],"{'dump': 'CC-MAIN-2014-41', 'url': 'http://tra..."
16,"Gade! Men jou jijman Seyè a ap rive! Jou sa a,...",<urn:uuid:20f6036f-814c-4c9f-9771-b015ff39d18a>,[],"{'dump': 'CC-MAIN-2017-13', 'url': 'http://www..."
17,"Ayiti 1 an apre, se tit yon konferans Lavwadla...",<urn:uuid:2797c047-9d82-4b32-9b32-307d56f4d886>,[],"{'dump': 'CC-MAIN-2021-04', 'url': 'https://ww..."
18,Jwenn yon gade pi pre ki jan anplwaye IRS te p...,<urn:uuid:b3aa0bde-35f9-44e7-9bb5-b080b0d63f24>,[],"{'dump': 'CC-MAIN-2022-21', 'url': 'https://ww..."
19,Bailey Ryder se yon enstriktè fè egzèsis vire ...,<urn:uuid:c6a203e2-7d30-4ac6-8992-085a24b65dd0>,[],"{'dump': 'CC-MAIN-2022-21', 'url': 'https://vi..."
20,Video a parèt sou Twitter nan hashtag HairFree...,<urn:uuid:30d82f46-7bff-42de-ae69-13a8b478b4b2>,[],"{'dump': 'CC-MAIN-2022-49', 'url': 'https://ww..."
21,"Zhejiang Feihu nouvo enèji teknoloji co, Ltd. ...",<urn:uuid:5ab23b62-d79c-4b68-91ba-94ed0ae5fa79>,[],"{'dump': 'CC-MAIN-2023-06', 'url': 'http://ht...."
22,[...]\nSèlman yon lane aprè Minis Naval Fransè...,<urn:uuid:60a7774e-4bf6-4bd3-8e79-64bc37f9d0ca>,[],"{'dump': 'CC-MAIN-2023-14', 'url': 'https://co..."
23,Yon fwa pa an chak fanmi dwe renouvle asirans ...,<urn:uuid:11bf4822-76f9-470f-94d4-f67e34d84963>,[],"{'dump': 'CC-MAIN-2016-22', 'url': 'https://ww..."
24,Jounal soti nan Slovaki. Lis prensipal jounal ...,<urn:uuid:d2fbcb09-b9c5-4f9f-9d37-77d07f937d74>,[],"{'dump': 'CC-MAIN-2018-30', 'url': 'https://ne..."
25,[...]\nYon reprezantan Depatman Deta peyi Etaz...,<urn:uuid:b5eee5b9-ef82-4f2f-9969-f09b3af315b4>,[],"{'dump': 'CC-MAIN-2021-31', 'url': 'https://ht..."
26,"Nan Montrouis, bò pòtay Latibonit. Sou twotwa ...",<urn:uuid:97d7216a-34b8-431a-ba13-d1dfabf410b1>,[],"{'dump': 'CC-MAIN-2021-31', 'url': 'https://me..."
27,Konpayi nou an te patisipe nan 16yèm Egzibisyo...,<urn:uuid:75c83649-5957-48f6-8d53-22a64a545b7c>,[],"{'dump': 'CC-MAIN-2022-33', 'url': 'http://ht...."
28,[...]\nEske m' pa lib? Eske m' pa yon apòt? Es...,<urn:uuid:1c960f8e-5812-4c47-8096-8fc0ccb120a1>,[],"{'dump': 'CC-MAIN-2016-44', 'url': 'https://ww..."
29,[...]\nYon compressésLè mande tretman medikaly...,<urn:uuid:55bc4ccb-fed0-4432-8075-8e95da787b42>,[],"{'dump': 'CC-MAIN-2021-04', 'url': 'http://m.h..."

#### b. Exploitation of statistics

**Fineweb2** (visual exploration)

D'après colonne "metadata":

-> pour fnw gcf, données vont de CC-MAIN-2013 à 2023 (avec surreprésentation de 2013 = 17/47, puis 2014/2027 ex aequo = 6/47, les autres plus que 3 textes par années);

-> pour fnw gcr, 2013 à 2024, autant de 2020/2017/2016 (6/21), les autres années égalent à deux ou un;

-> pour fwb hat, 2013 à 2023, majorité de 2014 avec 11/30, les autres de 4 à un.

In [13]:
# Glotcc (visual and explanatory stats)
df_glotcc_gcf

,content,warc-target-uri,warc-date,warc-record-id,quality-warnings,categories,identification-language,identification-prob,identification-consistency,script-percentage,num-sents,content-length,tlsh
0,"Popozision ki sòti nan Konsit LLKM za òganizé,...",https://www.llkm.org/bretmo/lam%C3%A9t%C3%A9yo...,2024-03-01T01:07:20Z,<urn:uuid:4ff66a63-2d90-4f0d-9dc5-46963283798d>,['short_sentences'],[],gcf-Latn,0.53,0.73,1.00,11,2648,tlsh:T17DF5E5516412CE9B1FCF90E10A3A8FA450187A4...
1,"Kantapou létjip Lafrans fanm, yo mennen bon mo...",https://potomitan.info/duranty/kreyolad395.php,2024-02-29T17:29:10Z,<urn:uuid:5a7bc6a7-e4c9-44af-9fd4-e5f40e215bb8>,['footer' 'short_sentences'],[],gcf-Latn,0.73,0.62,0.99,16,2402,tlsh:T196E154417444DF670BE742D1FCBEE98441707B5...
2,"Lanné 2017 ka komansé, lokazyon pou viré jété ...",https://www.timalo.com/bye-bye-2016/,2024-02-28T20:28:03Z,<urn:uuid:53594eb8-9c6e-4024-b01e-107176a306d9>,['header'],[],gcf-Latn,0.97,0.86,1.00,14,3251,tlsh:T1D4AF996141A0CBCB1FC320C25C1FDB90A828334...
3,ADN Awa ! [...]\nRandévou a sizè é dèmi dimate...,https://ugtg.org/spip.php?article657,2024-02-22T23:42:45Z,<urn:uuid:3c632070-bca0-4f71-b811-2183f1418fde>,['footer' 'short_sentences'],[],gcf-Latn,0.60,0.70,1.00,76,13151,tlsh:T1035F6F42E850DB8B0BCF22C3642FEE11046832A...
4,"Lendi bonmaten, anlo moun té anrajé anlè lawou...",https://potomitan.info/duranty/kreyolad592.php,2024-02-26T21:39:29Z,<urn:uuid:0703ddcb-3466-4020-af64-f4b88c50872f>,['footer' 'short_sentences'],[],gcf-Latn,0.64,0.64,1.00,14,2125,tlsh:T1BFF24F4197D4E7C70FD762E1683AAE8404A02B6...
5,House of Àṣẹ (pwononsé a-ché) sé on koté èspés...,https://www.houseofase.com/gp/,2024-02-29T23:58:27Z,<urn:uuid:a6499e62-8373-4535-806a-50016e48b78f>,['short_sentences'],[],gcf-Latn,0.86,0.62,1.00,8,1069,tlsh:T1CE96A411F041E10657C802E8653EEA402629248...
6,An ay fè on lantou Brisèl é an pa vwè pon-on m...,https://www.timalo.com/timalo-an-beljik/,2024-02-28T18:24:06Z,<urn:uuid:78f7cb3e-574e-4fa3-8412-d32dfb4b5a83>,[],[],gcf-Latn,0.99,1.00,0.99,7,1970,tlsh:T18C3710417651D3DB0B8F71D7182BEFC9583872C...
7,[...]\nMi zafè an péyi-la ! Misyé Louwa ka may...,http://creoles.free.fr/Cours/tichika.htm,2024-02-28T02:13:28Z,<urn:uuid:124db539-144b-4dbd-978b-cc66f5c214f7>,[],[],gcf-Latn,0.86,0.95,1.00,41,8870,tlsh:T1FC65B6028673D78B2FCB11C2152DEF88852C298...
8,Dimanch pasé tout moun té douvan télé-yo pou t...,https://potomitan.info/duranty/kreyolad955.php,2024-02-26T22:16:57Z,<urn:uuid:1ce24461-055e-4faa-9172-39fb6b3a6729>,['footer' 'short_sentences'],[],gcf-Latn,0.65,0.60,1.00,15,2063,tlsh:T18D7E3F417291CBBB2DD611F6382EED914C74228...
9,Aaaah arrété fè mwen chié dé labiè mwen brè\nO...,https://www.lyricsmania.com/an_kou_tombe_lyric...,2024-03-03T05:53:59Z,<urn:uuid:a4792ef2-6bd6-4aa0-ac49-8d3ff21d3bc9>,[],[],gcf-Latn,0.53,1.00,1.00,2,2213,tlsh:T1FB8C1E41F125EBDA27EB0AF29D29E5181958169...
10,Lasimenn pasé té ja ka ba’y nef jou moun té ka...,https://potomitan.info/duranty/kreyolad538.php,2024-03-01T21:17:20Z,<urn:uuid:870e3235-dc6a-4128-9f2c-bb39511e5695>,['footer' 'header' 'short_sentences'],[],gcf-Latn,0.50,0.62,0.99,16,2107,tlsh:T15F77094155E1E71807DB43D1A57D8E4818242B9...
11,[...]\nRandévou a sizè é dèmi dimaten a Kanpèc...,http://ugtg.org/spip.php?article657,2024-02-21T00:39:47Z,<urn:uuid:73f6a395-f788-44df-a106-89966e9ff536>,['footer' 'short_sentences'],[],gcf-Latn,0.61,0.69,1.00,77,13057,tlsh:T118919342F850DB8B0BCF22C3642FEE11046832A...
12,"Popozision ki sòti nan Konsit LLKM za òganizé,...",https://www.llkm.org/kontak/,2024-03-01T02:04:18Z,<urn:uuid:d759bbd2-ee8e-452b-9934-be6e5e6499cc>,['short_sentences'],[],gcf-Latn,0.53,0.73,1.00,11,2648,tlsh:T17DF5E5516412CE9B1FCF90E10A3A8FA450187A4...
13,Sé nan lanné 1981 an éti an krey manmay ki té ...,http://www.latribunedesantilles.net/article/28...,2024-02-28T21:34:28Z,<urn:uuid:ef8a3177-3e13-4bb4-8be8-0edf0ebcbd5c>,[],[],gcf-Latn,0.68,0.88,0.99,8,7529,tlsh:T12A6E39F16151DB770FCF50E26AEF4B94A814074...
14,"Senkan apré i pati an péyi san chapo, Neg fond...",https://potomitan.info/duranty/kreyolad476.php,2024-02-26T20:48:15Z,<urn:uuid:139c3f44-ce74-4fb9-a0e9-76be5f156041>,['footer' 'short_sentences'],[],gcf-Latn,0.73,0.65,0.99,17,1717,tlsh:T1F7A8A13154D1DB070BCF92D1751FEFD00428268...
15,"Sé sa anlo moun ka mandé, mé sa vré, lè an bag...",https://potomitan.info/duranty/kreyolad730.php,2024-02-29T17:19:33Z,<urn:uuid:586b6a37-44bf-49c4-b606-7b0aea248447>,['footer' 'short_sentences'],[],gcf-Latn,0.65,0.60,1.00,15,1788,tlsh:T1C50286318584FB431FDE10E22E7FDB508864338...
16,"« Manman, lagrev baré mwen, misié Michel pa lé...",https://www.llkm.org/mak-listw%C3%A8/f%C3%A9vr...,2024-03-01T02:17:13Z,<urn:uuid:573ff3d8-aaf7-4ee6-bb05-355928a2fb08>,[],[],gcf-Latn,0.73,0.74,1.00,23,5048,tlsh:T17A5674A19516DF9B2BCAA1E1196B9FD84028364...
17,"Magré mwa mas-la dit dépi lontan, ni anlo moun...",https://potomitan.info/duranty/kreyolad820.php,2024-02-26T21:57:02Z,<urn:uuid:d7bc313e-1118-408a-b470-506f714fdf24>,['footer' 'short_sentences'],[],gcf-Latn,0.66,0.67,0.99,18,2092,tlsh:T132EA98415200EB6B2BCD45D16D3DAB78682832C...
18,[...]\nOu sé on maléréz ki goumé pou lévé 9 pi...,https://www.nouvellesetincelles.fr/article/421...,2024-03-02T23:12:52Z,<urn:uuid:83a6517e-e63d-4e50-b0eb-0c159b6abbad>,[],[],gcf-Latn,0.53,0.64,0.99,11,3752,tlsh:T13EFC5A71A555D7902FF322824D2ECB590028714...
19,[...]\nPENGAD (Tansyon) ! On dosyé konplé ka f...,http://eritaj.org/bacs-creoles/preparation-a-l...,2024-02-26T20:58:56Z,<urn:uuid:29d52e56-ddb8-4ae1-9511-ca2abb04f812>,[],[],gcf-Latn,0.84,0.93,0.99,40,7654,tlsh:T144C163F173B4CF8B1FC610E3182E07746568134...
20,[...]\n« An ka ansényé fransé dèpi on dizenn l...,http://creoles.free.fr/Cours/sainteloi.htm,2024-02-28T03:55:25Z,<urn:uuid:562f04fb-0019-43e2-bbc6-545fbdda11f6>,[],[],gcf-Latn,0.90,0.75,1.00,4,1308,tlsh:T1D861B621423097864FC117C1181D4D16F00433C...
21,"Apré on Bac Litérè an Gwadloup, an pasé dé lan...",http://traduction-multilingue.com/index_kr.php...,2024-02-25T08:12:50Z,<urn:uuid:8feb089a-6db5-4160-9a49-f8ffbab66c80>,['short_sentences'],[],gcf-Latn,0.78,0.67,1.00,6,731,tlsh:T114DD2C01C041DA7B0BC520F5924E9154505477C...
22,"Misié té ka fè wol mò, pas anlo moun té lé tér...",https://potomitan.info/duranty/kreyolad380.php,2024-02-29T18:23:29Z,<urn:uuid:30147c2b-df12-4807-b2af-e9c3239b3a88>,['footer' 'short_sentences'],[],gcf-Latn,0.71,0.62,0.99,13,1796,tlsh:T1E94C73310010EB8B0FEE52DB357ECE49841C230...
23,Luil ésansiyèl a vétivè (Vetiveria zizanioides...,https://phytochemia.com/en/2020/10/28/on-vetiv...,2024-02-28T22:35:33Z,<urn:uuid:3a921ba7-bed6-43e6-bda6-2274141a7d5f>,[],[],gcf-Latn,0.89,0.89,1.00,9,5128,tlsh:T1075232B184BAD7631FCF62E3652EDFA46518228...
24,"Pou moun ki ka di kréyòl pé pa maké, sa pa vré...",https://bokantajenes.alychouette.com/2019/10/0...,2024-02-28T00:14:37Z,<urn:uuid:5cda3993-438c-4213-a308-9c499ad13ea1>,['footer' 'short_sentences'],[],gcf-Latn,0.77,0.84,0.98,19,2708,tlsh:T13A1361517721D7868FDEC1C61829DB78A268118...

In [15]:
print(list(df_glotcc_gcf.columns.values))

['content', 'warc-target-uri', 'warc-date', 'warc-record-id', 'quality-warnings', 'categories', 'identification-language', 'identification-prob', 'identification-consistency', 'script-percentage', 'num-sents', 'content-length', 'tlsh']

In [17]:
# faire la moyenne de 'identification-prob'
print(f"Mean of the language probabilty score for Glotcc gcf : {df_glotcc_gcf['identification-prob'].mean()}")
print(f"Min language probabilty score for Glotcc gcf : {df_glotcc_gcf['identification-prob'].min()}")
print(f"Max language probabilty score for Glotcc gcf : {df_glotcc_gcf['identification-prob'].max()}")
print(f"Standard Deviation of language propability score for Glotcc gcf : {np.std(list(df_glotcc_gcf['identification-prob']))}")

Mean of the language probabilty score for Glotcc gcf : 0.7148
Min language probabilty score for Glotcc gcf : 0.5
Max language probabilty score for Glotcc gcf : 0.99
Standard Deviation of language propability score for Glotcc gcf : 0.1409714864786493

In [23]:
print(f"Mean of the language probabilty score for Glotcc gcr : {df_glotcc_gcr['identification-prob'].mean()}")
print(f"Min language probabilty score for Glotcc gcr : {df_glotcc_gcr['identification-prob'].min()}")
print(f"Max language probabilty score for Glotcc gcr : {df_glotcc_gcr['identification-prob'].max()}")
print(f"Standard Deviation of language propability score for Glotcc gcr : {np.std(list(df_glotcc_gcr['identification-prob']))}")

Mean of the language probabilty score for Glotcc gcr : 0.833076923076923
Min language probabilty score for Glotcc gcr : 0.6
Max language probabilty score for Glotcc gcr : 1.0
Standard Deviation of language propability score for Glotcc gcr : 0.09024621154499979

In [25]:
print(f"Mean of the language probabilty score for Glotcc hat : {df_glotcc_hat['identification-prob'].mean()}")
print(f"Min language probabilty score for Glotcc hat : {df_glotcc_hat['identification-prob'].min()}")
print(f"Max language probabilty score for Glotcc hat : {df_glotcc_hat['identification-prob'].max()}")
print(f"Standard Deviation of language propability score for Glotcc hat : {np.std(list(df_glotcc_hat['identification-prob']))}")

Mean of the language probabilty score for Glotcc hat : 0.9046153846153845
Min language probabilty score for Glotcc hat : 0.66
Max language probabilty score for Glotcc hat : 1.0
Standard Deviation of language propability score for Glotcc hat : 0.10951750015516554

In [27]:
# faire la moyenne de 'num_sents'
print(f"Mean of the number of sentences for Glotcc gcf : {df_glotcc_gcf['num-sents'].mean()}")
print(f"Min number of sentences for Glotcc gcf : {df_glotcc_gcf['num-sents'].min()}")
print(f"Max number of sentences for Glotcc gcf : {df_glotcc_gcf['num-sents'].max()}")
print(f"Standard Deviation of the number of sentences for Glotcc gcf : {np.std(list(df_glotcc_gcf['num-sents']))}")

Mean of the number of sentences for Glotcc gcf : 19.64
Min number of sentences for Glotcc gcf : 2
Max number of sentences for Glotcc gcf : 77
Standard Deviation of the number of sentences for Glotcc gcf : 19.021840079235236

In [29]:
print(f"Mean of the number of sentences for Glotcc gcr : {df_glotcc_gcr['num-sents'].mean()}")
print(f"Min number of sentences for Glotcc gcr : {df_glotcc_gcr['num-sents'].min()}")
print(f"Max number of sentences for Glotcc gcr : {df_glotcc_gcr['num-sents'].max()}")
print(f"Standard Deviation of the number of sentences for Glotcc gcr : {np.std(list(df_glotcc_gcr['num-sents']))}")

Mean of the number of sentences for Glotcc gcr : 5.230769230769231
Min number of sentences for Glotcc gcr : 3
Max number of sentences for Glotcc gcr : 8
Standard Deviation of the number of sentences for Glotcc gcr : 1.5764539639937842

In [31]:
print(f"Mean of the number of sentence for Glotcc hat : {df_glotcc_hat['num-sents'].mean()}")
print(f"Min number of sentences for Glotcc hat : {df_glotcc_hat['num-sents'].min()}")
print(f"Max number of sentences for Glotcc hat : {df_glotcc_hat['num-sents'].max()}")
print(f"Standard Deviation of the number of sentence for Glotcc hat : {np.std(list(df_glotcc_hat['num-sents']))}")

Mean of the number of sentence for Glotcc hat : 25.46153846153846
Min number of sentences for Glotcc hat : 4
Max number of sentences for Glotcc hat : 68
Standard Deviation of the number of sentence for Glotcc hat : 20.930711276882423

### 2. Removal of unnecessary info, lang ID column added, concatenation of dataframe per corpus
#### a. Removal of all columns except text/content + iso code column added

In [34]:
# fineweb2
print(list(df_fnw_gcf.columns.values))

['text', 'id', 'media', 'metadata']

In [36]:
cols_to_remove = ["id", "media", "metadata"]
df_fnw_gcf = df_fnw_gcf.drop(columns=cols_to_remove)
df_fnw_gcr = df_fnw_gcr.drop(columns=cols_to_remove)
df_fnw_hat = df_fnw_hat.drop(columns=cols_to_remove)

In [38]:
df_fnw_gcf["iso-639-3"] = "gcf"
df_fnw_gcr["iso-639-3"] = "gcr"
df_fnw_hat["iso-639-3"] = "hat"

In [40]:
df_fnw_gcr

                                                 text iso-639-3
0   VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...       gcr
1   Lé ven senk mè démildis tout éléktér Sirinamye...       gcr
2   [...]\nALE LAVE TO PYE, RAFAYEL!!\nBABUN MOFU ...       gcr
3   [...]\nLé vent sis séktanm dé mil sét,annan vi...       gcr
4   Lo nou té wè lit bann moun-yan ki té jwenn ann...       gcr
5   KAYENN « MINING SYMPOSIUM »\nPoukisa yé rivé f...       gcr
6   Mo ka sonjé pronmyè fwè mo tandé sa zafè rakab...       gcr
7   Annou voyé kreyòl douvan douvan\n[...]\nMakak ...       gcr
8   Trwa variété di grenn di lanti kiltivé.\nSerte...       gcr
9   Mo té ké lé li sa artik-a ?\nChak lannen, Témw...       gcr
10  Mo té ké lé li sa artik-a ?\nLanmizik pou lado...       gcr
11  Abandonnen sa ki mal (1 Corinthiens 6:9, 10)\n...       gcr
12  Mo té ké lé li sa artik-a ?\nLiv ké brochir po...       gcr
13  [...]\nGrann Déprésyon-an (The Great Depressio...       gcr
14  [...]\nOun ion oben yon est sa roun atom oben ...       gcr
15  [...]\nJé di sosyété-a sa roun jé ki ka pratik...       gcr
16  [...]\nTablo péryodik dé éléman, égalman aplé ...       gcr
17  [...]\nNou ka aplé artiri ansanm-an dé arm kol...       gcr
18  [...]\nEntéraksyon fèb-a (osi aplé fòs fèb é p...       gcr
19  Sa paj ka konsèrné lannen 1156 di kalandriyé j...       gcr
20  Mé mo menm mo pa profité di sa bagaj-ya pyès. ...       gcr

In [42]:
# Glotcc
cols = ['warc-target-uri', 'warc-date', 'warc-record-id', 'quality-warnings', 'categories', 'identification-language', 'identification-prob', 'identification-consistency', 'script-percentage', 'num-sents', 'content-length', 'tlsh']
df_glotcc_gcf = df_glotcc_gcf.drop(columns=cols)
df_glotcc_gcr = df_glotcc_gcr.drop(columns=cols)
df_glotcc_hat = df_glotcc_hat.drop(columns=cols)

In [44]:
df_glotcc_gcf

                                              content
0   Popozision ki sòti nan Konsit LLKM za òganizé,...
1   Kantapou létjip Lafrans fanm, yo mennen bon mo...
2   Lanné 2017 ka komansé, lokazyon pou viré jété ...
3   ADN Awa ! [...]\nRandévou a sizè é dèmi dimate...
4   Lendi bonmaten, anlo moun té anrajé anlè lawou...
5   House of Àṣẹ (pwononsé a-ché) sé on koté èspés...
6   An ay fè on lantou Brisèl é an pa vwè pon-on m...
7   [...]\nMi zafè an péyi-la ! Misyé Louwa ka may...
8   Dimanch pasé tout moun té douvan télé-yo pou t...
9   Aaaah arrété fè mwen chié dé labiè mwen brè\nO...
10  Lasimenn pasé té ja ka ba’y nef jou moun té ka...
11  [...]\nRandévou a sizè é dèmi dimaten a Kanpèc...
12  Popozision ki sòti nan Konsit LLKM za òganizé,...
13  Sé nan lanné 1981 an éti an krey manmay ki té ...
14  Senkan apré i pati an péyi san chapo, Neg fond...
15  Sé sa anlo moun ka mandé, mé sa vré, lè an bag...
16  « Manman, lagrev baré mwen, misié Michel pa lé...
17  Magré mwa mas-la dit dépi lontan, ni anlo moun...
18  [...]\nOu sé on maléréz ki goumé pou lévé 9 pi...
19  [...]\nPENGAD (Tansyon) ! On dosyé konplé ka f...
20  [...]\n« An ka ansényé fransé dèpi on dizenn l...
21  Apré on Bac Litérè an Gwadloup, an pasé dé lan...
22  Misié té ka fè wol mò, pas anlo moun té lé tér...
23  Luil ésansiyèl a vétivè (Vetiveria zizanioides...
24  Pou moun ki ka di kréyòl pé pa maké, sa pa vré...

In [46]:
df_glotcc_gcf["iso-639-3"] = "gcf"
df_glotcc_gcr["iso-639-3"] = "gcr"
df_glotcc_hat["iso-639-3"] = "hat"

In [48]:
df_glotcc_hat

                                              content iso-639-3
0   [...]\nPaj sa a te tradui otomatikman soti nan...       hat
1   Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...       hat
2   Prezidan Joe Biden te byen resevwa lòt jou la ...       hat
3   Ningbo Hongtai te etabli an 2004, ki chita nan...       hat
4   Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...       hat
5   [...]\nPwofesè Michel DeGraff patisipe nan gwo...       hat
6   An menm tan an, li tou gen reyaksyon carboxyl ...       hat
7   Jou ki te 31 desanm 2019 la, kèk manm ANVA te ...       hat
8   Mat 4:13. Jésus te antre nan yon kannòt pou tr...       hat
9   Entwodiksyon Radiant P4 fleksib ekspozisyon di...       hat
10  * Remak: Inite koule a se estanda mèt kib/èdta...       hat
11  Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...       hat
12  2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...       hat

#### b. Concatenation per corpus + adding of corpus column

In [50]:
# concatenation fnw
df_fnw = pd.concat([df_fnw_gcf, df_fnw_gcr, df_fnw_hat], ignore_index=True)
df_fnw

                                                 text iso-639-3
0   [...] Sé jou-tala, ou sé di nou ka tonbé bien ...       gcf
1   [...]\nAn non pèp fransé-a,\nGouvèlman fransé-...       gcf
2   Man pé palé di Jean Bernabé an manniè ki lib d...       gcf
3   Counter Strike Source yo ka kriyéy osi CSS.\nS...       gcf
4   Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...       gcf
..                                                ...       ...
93  [...]\nYon reprezantan Depatman Deta peyi Etaz...       hat
94  Nan Montrouis, bò pòtay Latibonit. Sou twotwa ...       hat
95  Konpayi nou an te patisipe nan 16yèm Egzibisyo...       hat
96  [...]\nEske m' pa lib? Eske m' pa yon apòt? Es...       hat
97  [...]\nYon compressésLè mande tretman medikaly...       hat

[98 rows x 2 columns]

In [52]:
df_fnw["original-corpus"] = "fineweb2"
df_fnw

,text,iso-639-3,original-corpus
0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2
1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2
2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2
3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2
4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2
...,...,...,...
93,[...]\nYon reprezantan Depatman Deta peyi Etaz...,hat,fineweb2
94,"Nan Montrouis, bò pòtay Latibonit. Sou twotwa ...",hat,fineweb2
95,Konpayi nou an te patisipe nan 16yèm Egzibisyo...,hat,fineweb2
96,[...]\nEske m' pa lib? Eske m' pa yon apòt? Es...,hat,fineweb2
97,[...]\nYon compressésLè mande tretman medikaly...,hat,fineweb2

In [56]:
# concatenation glotcc
df_glotcc = pd.concat([df_glotcc_gcf, df_glotcc_gcr, df_glotcc_hat], ignore_index=True)
df_glotcc["original-corpus"] = "glotcc"
df_glotcc

,content,iso-639-3,original-corpus
0,"Popozision ki sòti nan Konsit LLKM za òganizé,...",gcf,glotcc
1,"Kantapou létjip Lafrans fanm, yo mennen bon mo...",gcf,glotcc
2,"Lanné 2017 ka komansé, lokazyon pou viré jété ...",gcf,glotcc
3,ADN Awa ! [...]\nRandévou a sizè é dèmi dimate...,gcf,glotcc
4,"Lendi bonmaten, anlo moun té anrajé anlè lawou...",gcf,glotcc
5,House of Àṣẹ (pwononsé a-ché) sé on koté èspés...,gcf,glotcc
6,An ay fè on lantou Brisèl é an pa vwè pon-on m...,gcf,glotcc
7,[...]\nMi zafè an péyi-la ! Misyé Louwa ka may...,gcf,glotcc
8,Dimanch pasé tout moun té douvan télé-yo pou t...,gcf,glotcc
9,Aaaah arrété fè mwen chié dé labiè mwen brè\nO...,gcf,glotcc
10,Lasimenn pasé té ja ka ba’y nef jou moun té ka...,gcf,glotcc
11,[...]\nRandévou a sizè é dèmi dimaten a Kanpèc...,gcf,glotcc
12,"Popozision ki sòti nan Konsit LLKM za òganizé,...",gcf,glotcc
13,Sé nan lanné 1981 an éti an krey manmay ki té ...,gcf,glotcc
14,"Senkan apré i pati an péyi san chapo, Neg fond...",gcf,glotcc
15,"Sé sa anlo moun ka mandé, mé sa vré, lè an bag...",gcf,glotcc
16,"« Manman, lagrev baré mwen, misié Michel pa lé...",gcf,glotcc
17,"Magré mwa mas-la dit dépi lontan, ni anlo moun...",gcf,glotcc
18,[...]\nOu sé on maléréz ki goumé pou lévé 9 pi...,gcf,glotcc
19,[...]\nPENGAD (Tansyon) ! On dosyé konplé ka f...,gcf,glotcc
20,[...]\n« An ka ansényé fransé dèpi on dizenn l...,gcf,glotcc
21,"Apré on Bac Litérè an Gwadloup, an pasé dé lan...",gcf,glotcc
22,"Misié té ka fè wol mò, pas anlo moun té lé tér...",gcf,glotcc
23,Luil ésansiyèl a vétivè (Vetiveria zizanioides...,gcf,glotcc
24,"Pou moun ki ka di kréyòl pé pa maké, sa pa vré...",gcf,glotcc
25,Jupiter sa roun planèt jéyant gazéz. A pli grò...,gcr,glotcc
26,"Hiver : kanpangn di Boleslas III Bouche-Torse,...",gcr,glotcc
27,Friedrich Wilhelm Nietzsche (prounonsé [ˈfʁiːd...,gcr,glotcc
28,Rock-a sa roun janr mizikal ki aparèt andan la...,gcr,glotcc
29,"Adi Shankara (sanskri : Ādi Śaṅkara, devanagar...",gcr,glotcc
30,Jen : èspédisyon di Saladin à lès-a di Jourdai...,gcr,glotcc
31,"Bahamas, an form long Commonwealth dé Bahamas,...",gcr,glotcc
32,"10 mè : lanprò-a di Mali Kanga Moussa, ki pati...",gcr,glotcc
33,"21 mè : dé navir fransé, ki koumandé pa August...",gcr,glotcc
34,26 jen : Palman ékosè-a ka ògtrwayé monnonpòl-...,gcr,glotcc
35,Bondjé ka dézigné oun fika oben fòs souprenm k...,gcr,glotcc
36,Jayinism-an oben jinism-an (du sanskrit : जैनम...,gcr,glotcc
37,11 janvyé : tout koumèrs dirèk ant Filipin-yan...,gcr,glotcc
38,[...]\nPaj sa a te tradui otomatikman soti nan...,hat,glotcc
39,Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...,hat,glotcc
40,Prezidan Joe Biden te byen resevwa lòt jou la ...,hat,glotcc
41,"Ningbo Hongtai te etabli an 2004, ki chita nan...",hat,glotcc
42,Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...,hat,glotcc
43,[...]\nPwofesè Michel DeGraff patisipe nan gwo...,hat,glotcc
44,"An menm tan an, li tou gen reyaksyon carboxyl ...",hat,glotcc
45,"Jou ki te 31 desanm 2019 la, kèk manm ANVA te ...",hat,glotcc
46,Mat 4:13. Jésus te antre nan yon kannòt pou tr...,hat,glotcc
47,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
48,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
49,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
50,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [58]:
# final concatenation of the two dataframes 
df_glotcc = df_glotcc.rename(columns={"content": "text"}) # change glotcc 'content' column header into 'text', to align with fineweb2
df_fnw_glotcc = pd.concat([df_fnw, df_glotcc], ignore_index=True)
df_fnw_glotcc

,text,iso-639-3,original-corpus
0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2
1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2
2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2
3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2
4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2
...,...,...,...
144,Mat 4:13. Jésus te antre nan yon kannòt pou tr...,hat,glotcc
145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [126]:
print(df_fnw_glotcc["iso-639-3"].value_counts())

iso-639-3
gcf    72
hat    43
gcr    34
Name: count, dtype: int64

In [60]:
print(df_fnw_glotcc["original-corpus"].value_counts())

original-corpus
fineweb2    98
glotcc      51
Name: count, dtype: int64

In [90]:
# adding index as columns
df_fnw_glotcc.reset_index(level=0, inplace=True)
df_fnw_glotcc

,index,text,iso-639-3,original-corpus
0,0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2
1,1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2
2,2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2
3,3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2
4,4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2
...,...,...,...,...
144,144,Mat 4:13. Jésus te antre nan yon kannòt pou tr...,hat,glotcc
145,145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
146,146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
147,147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
148,148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [92]:
df_fnw_glotcc.to_csv("fineweb2_glotcc_4C.csv", index=False)

### 3. Spacy - Count the number of sentences per language

In [80]:
# count split lang and count text per lang before
nlp = spacy.blank("xx")
nlp.add_pipe("sentencizer")

In [66]:
# Group texts by iso-code and concatenate into a single string
grouped = df_fnw_glotcc.groupby("iso-639-3")["text"].apply(" ".join)
print(grouped)

iso-639-3
gcf    [...] Sé jou-tala, ou sé di nou ka tonbé bien ...
gcr    VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...
hat    [...]\nLOS ANGELES, USA (defend.ht) - Sèz Iniv...
Name: text, dtype: object

In [82]:
doc_gcf = nlp(grouped["gcf"])
doc_gcr = nlp(grouped["gcr"])
doc_hat = nlp(grouped["hat"])
print(type(doc_hat))

<class 'spacy.tokens.doc.Doc'>

In [84]:
print(f"Number of sentences for gcf: {len(list(doc_gcf.sents))} \nNumber of sentences for gcr: {len(list(doc_gcr.sents))} \nNumber of sentences for hat: {len(list(doc_hat.sents))}")

Number of sentences for gcf: 2044
Number of sentences for gcr: 479
Number of sentences for hat: 1275

In [86]:
# another try with blank fr.
nlp = spacy.blank("fr")
nlp.add_pipe("sentencizer")
doc_gcf = nlp(grouped["gcf"])
doc_gcr = nlp(grouped["gcr"])
doc_hat = nlp(grouped["hat"])
print(f"Number of sentences for gcf: {len(list(doc_gcf.sents))} \nNumber of sentences for gcr: {len(list(doc_gcr.sents))} \nNumber of sentences for hat: {len(list(doc_hat.sents))}")

Number of sentences for gcf: 1985
Number of sentences for gcr: 475
Number of sentences for hat: 1272

In [88]:
# last try with little French model
nlp = spacy.load("fr_core_news_sm")
doc_gcf = nlp(grouped["gcf"])
doc_gcr = nlp(grouped["gcr"])
doc_hat = nlp(grouped["hat"])
print(f"Number of sentences for gcf: {len(list(doc_gcf.sents))} \nNumber of sentences for gcr: {len(list(doc_gcr.sents))} \nNumber of sentences for hat: {len(list(doc_hat.sents))}")

Number of sentences for gcf: 4554
Number of sentences for gcr: 1118
Number of sentences for hat: 3310